[profile.default]
src = 'contracts'
out = 'out'
libs = ["node_modules", "lib"]
test = 'test-foundry'
cache_path = 'forge-cache'
solc_version = '0.8.25'
optimizer = true
optimizer_runs = 1000000
via_ir = true
evm_version = 'cancun'
fs_permissions = [{ access = "read", path = "./"}]
# Only run tests from test-foundry directory
no_match_path = "contracts/tests/*"

[profile.ci]
fuzz = { runs = 10000 }
invariant = { runs = 1000 }

[fmt]
line_length = 120
tab_width = 4
bracket_spacing = true
