/* Autogenerated file. Do not edit manually. */
/* tslint:disable */
/* eslint-disable */

import BN from "bn.js";
import { EventData, PastEventOptions } from "web3-eth-contract";

export interface AddressSetMockContract
  extends Truffle.Contract<AddressSetMockInstance> {
  "new"(meta?: Truffle.TransactionDetails): Promise<AddressSetMockInstance>;
}

type AllEvents = never;

export interface AddressSetMockInstance extends Truffle.ContractInstance {
  add: {
    (item: string, txDetails?: Truffle.TransactionDetails): Promise<
      Truffle.TransactionResponse<AllEvents>
    >;
    call(
      item: string,
      txDetails?: Truffle.TransactionDetails
    ): Promise<boolean>;
    sendTransaction(
      item: string,
      txDetails?: Truffle.TransactionDetails
    ): Promise<string>;
    estimateGas(
      item: string,
      txDetails?: Truffle.TransactionDetails
    ): Promise<number>;
  };

  at(
    index: number | BN | string,
    txDetails?: Truffle.TransactionDetails
  ): Promise<string>;

  contains(
    item: string,
    txDetails?: Truffle.TransactionDetails
  ): Promise<boolean>;

  length(txDetails?: Truffle.TransactionDetails): Promise<BN>;

  remove: {
    (item: string, txDetails?: Truffle.TransactionDetails): Promise<
      Truffle.TransactionResponse<AllEvents>
    >;
    call(
      item: string,
      txDetails?: Truffle.TransactionDetails
    ): Promise<boolean>;
    sendTransaction(
      item: string,
      txDetails?: Truffle.TransactionDetails
    ): Promise<string>;
    estimateGas(
      item: string,
      txDetails?: Truffle.TransactionDetails
    ): Promise<number>;
  };

  methods: {
    add: {
      (item: string, txDetails?: Truffle.TransactionDetails): Promise<
        Truffle.TransactionResponse<AllEvents>
      >;
      call(
        item: string,
        txDetails?: Truffle.TransactionDetails
      ): Promise<boolean>;
      sendTransaction(
        item: string,
        txDetails?: Truffle.TransactionDetails
      ): Promise<string>;
      estimateGas(
        item: string,
        txDetails?: Truffle.TransactionDetails
      ): Promise<number>;
    };

    at(
      index: number | BN | string,
      txDetails?: Truffle.TransactionDetails
    ): Promise<string>;

    contains(
      item: string,
      txDetails?: Truffle.TransactionDetails
    ): Promise<boolean>;

    length(txDetails?: Truffle.TransactionDetails): Promise<BN>;

    remove: {
      (item: string, txDetails?: Truffle.TransactionDetails): Promise<
        Truffle.TransactionResponse<AllEvents>
      >;
      call(
        item: string,
        txDetails?: Truffle.TransactionDetails
      ): Promise<boolean>;
      sendTransaction(
        item: string,
        txDetails?: Truffle.TransactionDetails
      ): Promise<string>;
      estimateGas(
        item: string,
        txDetails?: Truffle.TransactionDetails
      ): Promise<number>;
    };
  };

  getPastEvents(event: string): Promise<EventData[]>;
  getPastEvents(
    event: string,
    options: PastEventOptions,
    callback: (error: Error, event: EventData) => void
  ): Promise<EventData[]>;
  getPastEvents(event: string, options: PastEventOptions): Promise<EventData[]>;
  getPastEvents(
    event: string,
    callback: (error: Error, event: EventData) => void
  ): Promise<EventData[]>;
}
