/* Autogenerated file. Do not edit manually. */
/* tslint:disable */
/* eslint-disable */

import BN from "bn.js";
import { EventData, PastEventOptions } from "web3-eth-contract";

export interface IDaiLikePermitContract
  extends Truffle.Contract<IDaiLikePermitInstance> {
  "new"(meta?: Truffle.TransactionDetails): Promise<IDaiLikePermitInstance>;
}

type AllEvents = never;

export interface IDaiLikePermitInstance extends Truffle.ContractInstance {
  permit: {
    (
      holder: string,
      spender: string,
      nonce: number | BN | string,
      expiry: number | BN | string,
      allowed: boolean,
      v: number | BN | string,
      r: string,
      s: string,
      txDetails?: Truffle.TransactionDetails
    ): Promise<Truffle.TransactionResponse<AllEvents>>;
    call(
      holder: string,
      spender: string,
      nonce: number | BN | string,
      expiry: number | BN | string,
      allowed: boolean,
      v: number | BN | string,
      r: string,
      s: string,
      txDetails?: Truffle.TransactionDetails
    ): Promise<void>;
    sendTransaction(
      holder: string,
      spender: string,
      nonce: number | BN | string,
      expiry: number | BN | string,
      allowed: boolean,
      v: number | BN | string,
      r: string,
      s: string,
      txDetails?: Truffle.TransactionDetails
    ): Promise<string>;
    estimateGas(
      holder: string,
      spender: string,
      nonce: number | BN | string,
      expiry: number | BN | string,
      allowed: boolean,
      v: number | BN | string,
      r: string,
      s: string,
      txDetails?: Truffle.TransactionDetails
    ): Promise<number>;
  };

  methods: {
    permit: {
      (
        holder: string,
        spender: string,
        nonce: number | BN | string,
        expiry: number | BN | string,
        allowed: boolean,
        v: number | BN | string,
        r: string,
        s: string,
        txDetails?: Truffle.TransactionDetails
      ): Promise<Truffle.TransactionResponse<AllEvents>>;
      call(
        holder: string,
        spender: string,
        nonce: number | BN | string,
        expiry: number | BN | string,
        allowed: boolean,
        v: number | BN | string,
        r: string,
        s: string,
        txDetails?: Truffle.TransactionDetails
      ): Promise<void>;
      sendTransaction(
        holder: string,
        spender: string,
        nonce: number | BN | string,
        expiry: number | BN | string,
        allowed: boolean,
        v: number | BN | string,
        r: string,
        s: string,
        txDetails?: Truffle.TransactionDetails
      ): Promise<string>;
      estimateGas(
        holder: string,
        spender: string,
        nonce: number | BN | string,
        expiry: number | BN | string,
        allowed: boolean,
        v: number | BN | string,
        r: string,
        s: string,
        txDetails?: Truffle.TransactionDetails
      ): Promise<number>;
    };
  };

  getPastEvents(event: string): Promise<EventData[]>;
  getPastEvents(
    event: string,
    options: PastEventOptions,
    callback: (error: Error, event: EventData) => void
  ): Promise<EventData[]>;
  getPastEvents(event: string, options: PastEventOptions): Promise<EventData[]>;
  getPastEvents(
    event: string,
    callback: (error: Error, event: EventData) => void
  ): Promise<EventData[]>;
}
