/* Autogenerated file. Do not edit manually. */
/* tslint:disable */
/* eslint-disable */

import BN from "bn.js";
import { EventData, PastEventOptions } from "web3-eth-contract";

export interface StringUtilTestContract
  extends Truffle.Contract<StringUtilTestInstance> {
  "new"(meta?: Truffle.TransactionDetails): Promise<StringUtilTestInstance>;
}

type AllEvents = never;

export interface StringUtilTestInstance extends Truffle.ContractInstance {
  toHex(
    value: number | BN | string,
    expectedGasCost: number | BN | string,
    txDetails?: Truffle.TransactionDetails
  ): Promise<string>;

  toHexBytes(
    data: string,
    expectedGasCost: number | BN | string,
    txDetails?: Truffle.TransactionDetails
  ): Promise<string>;

  toHexNaive(
    value: number | BN | string,
    expectedGasCost: number | BN | string,
    txDetails?: Truffle.TransactionDetails
  ): Promise<string>;

  toHexNaiveBytes(
    data: string,
    expectedGasCost: number | BN | string,
    txDetails?: Truffle.TransactionDetails
  ): Promise<string>;

  methods: {
    toHex(
      value: number | BN | string,
      expectedGasCost: number | BN | string,
      txDetails?: Truffle.TransactionDetails
    ): Promise<string>;

    toHexBytes(
      data: string,
      expectedGasCost: number | BN | string,
      txDetails?: Truffle.TransactionDetails
    ): Promise<string>;

    toHexNaive(
      value: number | BN | string,
      expectedGasCost: number | BN | string,
      txDetails?: Truffle.TransactionDetails
    ): Promise<string>;

    toHexNaiveBytes(
      data: string,
      expectedGasCost: number | BN | string,
      txDetails?: Truffle.TransactionDetails
    ): Promise<string>;
  };

  getPastEvents(event: string): Promise<EventData[]>;
  getPastEvents(
    event: string,
    options: PastEventOptions,
    callback: (error: Error, event: EventData) => void
  ): Promise<EventData[]>;
  getPastEvents(event: string, options: PastEventOptions): Promise<EventData[]>;
  getPastEvents(
    event: string,
    callback: (error: Error, event: EventData) => void
  ): Promise<EventData[]>;
}
