name: PUBLISH

on:
  workflow_dispatch:

permissions:
  contents: read
  id-token: write
  packages: write

jobs:
  publish-npmjs:
    uses: 1inch/ci-workflow-protocol/.github/workflows/publish.yml@master

  publish-github:
    uses: 1inch/ci-workflow-protocol/.github/workflows/publish-github-packages.yml@master
