name: CREATE_RELEASE

on:
  workflow_dispatch:

permissions:
  contents: write

jobs:
  create-release:
    uses: 1inch/ci-workflow-protocol/.github/workflows/release.yml@v1.0.0
    with:
      changelog: true
